spring:
  application:
    name: course-service
aws:
  region: ${aws.region}
  dynamodb:
    endpoint: ${aws.dynamodb.endpoint}

management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080

